"""Emit the Studio-side script that stages a scene and plays it.

``KeyframeSequenceProvider:RegisterKeyframeSequence`` hands back a temporary
asset id for a KeyframeSequence that lives only in the open place, which is
what makes a multi-character cinematic previewable without uploading anything.
The ids are Studio-only by design, so this script is for iterating; publishing
each animation the normal way is what ships.
"""

from __future__ import annotations

from pathlib import Path

from .build import BuiltScene

HEADER = """\
--!strict
-- Generated by Linen. Do not edit by hand; regenerate with `linen scene`.
--
-- Setup, once:
--   1. Import each {name}_<Actor>.rbxmx (Animation Editor > Import > From File),
--      or drag the files into {folder}.
--   2. Put one rig per actor in Workspace, named exactly as below.
--   3. Run this from the Command Bar or as a Script, in Studio.
--
-- The animation ids this registers are temporary and Studio-only. Publish each
-- KeyframeSequence normally when the scene is finished.
"""


def scene_script(built: BuiltScene, *, folder: str = "ServerStorage.LinenAnimations") -> str:
    scene = built.scene
    lines: list[str] = [HEADER.format(name=scene.name, folder=folder), ""]

    lines.append(f'local SCENE_NAME = "{_escape(scene.name)}"')
    lines.append(f"local FOLDER_PATH = \"{_escape(folder)}\"")
    lines.append(f"local FPS = {scene.fps:g}")
    lines.append(f"local DURATION = {built.duration:.4f}")
    lines.append("")
    lines.append("local STAGE = {")
    for actor in scene.actors:
        x, y, z = actor.position
        facing = _facing_literal(actor.facing)
        lines.append(
            f'\t{{ name = "{_escape(actor.name)}", rig = "{actor.rig.upper()}", '
            f"position = Vector3.new({x:g}, {y:g}, {z:g}), facing = {facing} }},"
        )
    lines.append("}")
    lines.append("")
    lines.append("-- Cue sheet, for reference when retiming by hand.")
    lines.append("local CUES = {")
    for entry in built.schedule:
        summary = _escape((entry.cue.prompt or entry.plan.name)[:60])
        lines.append(
            f'\t{{ id = "{_escape(entry.cue.id)}", actor = "{_escape(entry.cue.actor)}", '
            f"start = {entry.start:.3f}, stop = {entry.end:.3f}, "
            f'what = "{summary}" }},'
        )
    lines.append("}")
    lines.append("")
    lines.append(BODY)
    return "\n".join(lines)


BODY = '''\
local KeyframeSequenceProvider = game:GetService("KeyframeSequenceProvider")

-- "ServerStorage.LinenAnimations" and friends. The first segment may be a
-- service, which is not a child of game until it exists, so it gets a
-- GetService fallback; deeper segments are ordinary children.
local function resolve(path: string): Instance?
\tlocal current: Instance = game
\tfor segment in string.gmatch(path, "[^%.]+") do
\t\tlocal child: Instance? = current:FindFirstChild(segment)
\t\tif child == nil and current == game then
\t\t\tlocal ok, service = pcall(game.GetService, game, segment)
\t\t\tif ok then
\t\t\t\tchild = service
\t\t\tend
\t\tend
\t\tif child == nil then
\t\t\treturn nil
\t\tend
\t\tcurrent = child
\tend
\treturn current
end

local folder = resolve(FOLDER_PATH)
if folder == nil then
\terror(string.format("Linen: no %s — import the .rbxmx files there first.", FOLDER_PATH))
end

local tracks: { AnimationTrack } = {}

for _, entry in STAGE do
\tlocal model = workspace:FindFirstChild(entry.name)
\tif model == nil or not model:IsA("Model") then
\t\twarn(string.format("Linen: no rig named %q in Workspace — skipping.", entry.name))
\t\tcontinue
\tend

\t-- Stage the rig. Facing another actor is resolved now, so moving either of
\t-- them and re-running is enough to re-aim both.
\tlocal look = entry.position
\tif typeof(entry.facing) == "string" then
\t\tlocal other = workspace:FindFirstChild(entry.facing)
\t\tif other and other:IsA("Model") then
\t\t\tlook = other:GetPivot().Position
\t\tend
\telseif typeof(entry.facing) == "number" then
\t\tlook = entry.position + Vector3.new(math.sin(math.rad(entry.facing)), 0, -math.cos(math.rad(entry.facing)))
\tend

\tif look ~= entry.position then
\t\tmodel:PivotTo(CFrame.lookAt(entry.position, Vector3.new(look.X, entry.position.Y, look.Z)))
\telse
\t\tmodel:PivotTo(CFrame.new(entry.position))
\tend

\tlocal humanoid = model:FindFirstChildOfClass("Humanoid")
\tlocal animator = humanoid and humanoid:FindFirstChildOfClass("Animator")
\tif animator == nil then
\t\twarn(string.format("Linen: %q has no Humanoid/Animator — skipping.", entry.name))
\t\tcontinue
\tend

\tlocal sequenceName = string.format("%s_%s", SCENE_NAME, entry.name)
\tlocal sequence = folder:FindFirstChild(sequenceName)
\tif sequence == nil or not sequence:IsA("KeyframeSequence") then
\t\twarn(string.format("Linen: no KeyframeSequence %q in %s — skipping.", sequenceName, FOLDER_PATH))
\t\tcontinue
\tend

\tlocal animation = Instance.new("Animation")
\tanimation.Name = sequenceName
\tanimation.AnimationId = KeyframeSequenceProvider:RegisterKeyframeSequence(sequence)

\tlocal track = animator:LoadAnimation(animation)
\ttrack.Priority = Enum.AnimationPriority.Action4
\ttrack.Looped = false
\ttable.insert(tracks, track)
end

-- Every actor starts on the same frame. One track each, all begun together,
-- is the only arrangement that cannot drift over a long take.
for _, track in tracks do
\ttrack:Play(0)
end

print(string.format("Linen: playing %q — %d actors, %.2fs, %d cues.", SCENE_NAME, #tracks, DURATION, #CUES))
'''


def write_scene_script(
    built: BuiltScene, path: str | Path, *, folder: str = "ServerStorage.LinenAnimations"
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(scene_script(built, folder=folder))
    return path


def _facing_literal(facing: str | float | None) -> str:
    if facing is None:
        return "nil"
    if isinstance(facing, str):
        return f'"{_escape(facing)}"'
    return f"{float(facing):g}"


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
