"""Emit the Studio-side script that stages a scene and plays it.

``KeyframeSequenceProvider:RegisterKeyframeSequence`` hands back a temporary
asset id for a KeyframeSequence that lives only in the open place, which is
what makes a multi-character cinematic previewable without uploading anything.
The ids are Studio-only by design, so this script is for iterating; publishing
each animation the normal way is what ships.
"""

from __future__ import annotations

from pathlib import Path

from .build import BuiltScene
from .player import BODY

HEADER = """\
--!strict
-- Generated by Linen. Do not edit by hand; regenerate with `linen scene`.
--
-- Setup, once:
--   1. Import each {name}_<Actor>.rbxmx (Animation Editor > Import > From File),
--      or drag the files into {folder}.
--   2. Put one rig per actor in Workspace, named exactly as below.
--   3. Run this from the Command Bar or as a Script, in Studio.
--
-- The animation ids this registers are temporary and Studio-only. Publish each
-- KeyframeSequence normally when the scene is finished.
"""


def scene_script(built: BuiltScene, *, folder: str = "ServerStorage.LinenAnimations") -> str:
    scene = built.scene
    lines: list[str] = [HEADER.format(name=scene.name, folder=folder), ""]

    lines.append(f'local SCENE_NAME = "{_escape(scene.name)}"')
    lines.append(f"local FOLDER_PATH = \"{_escape(folder)}\"")
    lines.append(f"local FPS = {scene.fps:g}")
    lines.append(f"local DURATION = {built.duration:.4f}")
    lines.append("")
    lines.append("local STAGE = {")
    for actor in scene.actors:
        x, y, z = actor.position
        facing = _facing_literal(actor.facing)
        lines.append(
            f'\t{{ name = "{_escape(actor.name)}", rig = "{actor.rig.upper()}", '
            f"position = Vector3.new({x:g}, {y:g}, {z:g}), facing = {facing} }},"
        )
    lines.append("}")
    lines.append("")
    lines.append("-- Cue sheet, for reference when retiming by hand.")
    lines.append("local CUES = {")
    for entry in built.schedule:
        summary = _escape((entry.cue.prompt or entry.plan.name)[:60])
        lines.append(
            f'\t{{ id = "{_escape(entry.cue.id)}", actor = "{_escape(entry.cue.actor)}", '
            f"start = {entry.start:.3f}, stop = {entry.end:.3f}, "
            f'what = "{summary}" }},'
        )
    lines.append("}")
    lines.append("")

    lines.append("local SHOTS = {")
    for shot in scene.shots:
        x, y, z = shot.position
        dx, dy, dz = shot.drift
        lines.append(
            f'\t{{ id = "{_escape(shot.id)}", position = Vector3.new({x:g}, {y:g}, {z:g}), '
            f'lookAt = "{_escape(shot.look_at)}", fov = {shot.fov:g}, blend = {shot.blend:g}, '
            f"drift = Vector3.new({dx:g}, {dy:g}, {dz:g}) }},"
        )
    lines.append("}")
    lines.append("")

    lines.append("local PROPS = {")
    for prop in scene.props:
        gx, gy, gz = prop.grip
        held = f'"{_escape(prop.held_by)}"' if prop.held_by else "nil"
        lines.append(
            f'\t{{ name = "{_escape(prop.name)}", source = "{_escape(prop.source)}", '
            f'heldBy = {held}, attachTo = "{_escape(prop.attach_to)}", '
            f"grip = Vector3.new({gx:g}, {gy:g}, {gz:g}) }},"
        )
    lines.append("}")
    lines.append("")

    lines.append("-- Events with no actor: camera cuts and world effects.")
    lines.append("local DIRECTOR = {")
    for when, event in built.director:
        actor = f'"{_escape(event.actor)}"' if event.actor else "nil"
        lines.append(
            f'\t{{ at = {when:g}, kind = "{event.kind}", '
            f'value = "{_escape(event.marker_value())}", actor = {actor} }},'
        )
    lines.append("}")
    lines.append("")

    lines.append("-- Named expressions to FACS pose blends, so scenes stay readable.")
    lines.append("local EXPRESSIONS: { [string]: { [string]: number } } = {")
    for name, poses in _FACS.items():
        entries = ", ".join(f"{k} = {v:g}" for k, v in poses.items())
        lines.append(f"\t{name} = {{ {entries} }},")
    lines.append("}")
    lines.append("")

    lines.append(BODY)
    return "\n".join(lines)


#: A small, deliberate subset of the 50 FACS poses — enough to read at Roblox
#: camera distances, and named so a scene never mentions a coefficient.
_FACS: dict[str, dict[str, float]] = {
    "neutral": {},
    "smug": {"LeftLipCornerPuller": 0.75, "RightLipCornerPuller": 0.2, "LeftBrowLowerer": 0.25},
    "angry": {"LeftBrowLowerer": 0.9, "RightBrowLowerer": 0.9, "LipPressor": 0.6, "NoseWrinkler": 0.4},
    "afraid": {"LeftOuterBrowRaiser": 0.8, "RightOuterBrowRaiser": 0.8, "LeftEyeUpperLidRaiser": 0.9, "RightEyeUpperLidRaiser": 0.9, "JawDrop": 0.35},
    "surprised": {"LeftInnerBrowRaiser": 1.0, "RightInnerBrowRaiser": 1.0, "JawDrop": 0.5},
    "pain": {"LeftEyeClosed": 0.85, "RightEyeClosed": 0.85, "NoseWrinkler": 0.7, "LipStretcher": 0.5},
    "determined": {"LeftBrowLowerer": 0.5, "RightBrowLowerer": 0.5, "LipPressor": 0.4},
    "laughing": {"LeftLipCornerPuller": 1.0, "RightLipCornerPuller": 1.0, "JawDrop": 0.6, "LeftCheekRaiser": 0.7, "RightCheekRaiser": 0.7},
    "sad": {"LeftInnerBrowRaiser": 0.8, "RightInnerBrowRaiser": 0.8, "LeftLipCornerDepressor": 0.6, "RightLipCornerDepressor": 0.6},
}


def write_scene_script(
    built: BuiltScene, path: str | Path, *, folder: str = "ServerStorage.LinenAnimations"
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(scene_script(built, folder=folder))
    return path


def _facing_literal(facing: str | float | None) -> str:
    if facing is None:
        return "nil"
    if isinstance(facing, str):
        return f'"{_escape(facing)}"'
    return f"{float(facing):g}"


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
