"""Emit the Studio-side script that stages a scene and plays it.

``KeyframeSequenceProvider:RegisterKeyframeSequence`` hands back a temporary
asset id for a KeyframeSequence that lives only in the open place, which is
what makes a multi-character cinematic previewable without uploading anything.
The ids are Studio-only by design, so this script is for iterating; publishing
each animation the normal way is what ships.
"""

from __future__ import annotations

from pathlib import Path

from .audio import SpottingSheet
from .build import BuiltScene
from .player import BODY

HEADER = """\
--!strict
-- Generated by Linen. Do not edit by hand; regenerate with `linen scene`.
--
-- THIS IS A LOCALSCRIPT. It drives the camera, and a camera only exists on a
-- client: `workspace.CurrentCamera` is nil on a server, so the same code as a
-- Script stages the bodies and then shows nobody anything, with no error.
--
-- Setup, once:
--   1. Import each {name}_<Actor>.rbxmx (Animation Editor > Import > From File),
--      or drag the files into {folder}.
--   2. Put one rig per actor in Workspace, named exactly as below.
--   3. Paste this into a LocalScript in StarterPlayer > StarterPlayerScripts,
--      or run it from the Command Bar in Studio to preview.
--
-- Without published ids this registers Studio-only animations. Pass
-- `linen scene --animations publish.json` once they are published, and the
-- same script plays in a live game.
"""


def scene_script(
    built: BuiltScene,
    *,
    folder: str = "ServerStorage.LinenAnimations",
    sheet: SpottingSheet | None = None,
    mapping: dict[str, str] | None = None,
    animations: dict[str, str] | None = None,
) -> str:
    scene = built.scene
    lines: list[str] = [HEADER.format(name=scene.name, folder=folder), ""]

    lines.append(f'local SCENE_NAME = "{_escape(scene.name)}"')
    lines.append(f"local FOLDER_PATH = \"{_escape(folder)}\"")
    lines.append(f"local FPS = {scene.fps:g}")
    lines.append(f"local DURATION = {built.duration:.4f}")
    lines.append("")
    lines.append(
        "local STAGE: { { name: string, rig: string, position: Vector3, facing: any } } = {"
    )
    for actor in scene.actors:
        x, y, z = actor.position
        facing = _facing_literal(actor.facing)
        lines.append(
            f'\t{{ name = "{_escape(actor.name)}", rig = "{actor.rig.upper()}", '
            f"position = Vector3.new({x:g}, {y:g}, {z:g}), facing = {facing} }},"
        )
    lines.append("}")
    lines.append("")
    # Published ids, per actor. Empty means "register the KeyframeSequence",
    # which only Studio can do — so an empty table is a Studio-only scene, and
    # the script says so rather than going quietly still on a live server.
    lines.append(
        "-- Published animation ids, per actor. Empty: the script falls back to"
    )
    lines.append(
        "-- registering the KeyframeSequences, which works in Studio only."
    )
    lines.append("local ANIMATION_IDS: { [string]: string } = {")
    for actor in scene.actors:
        asset = (animations or {}).get(actor.name, "")
        if asset:
            lines.append(f'\t["{_escape(actor.name)}"] = "{_escape(asset)}",')
    lines.append("}")
    lines.append("")
    # The facial performance, generated: expressions eased, mouths driven from
    # the dialogue's own syllables, blinks underneath. Driven per frame rather
    # than written into the animation, because how a KeyframeSequence stores
    # facial tracks is not documented anywhere this could be checked against.
    lines.append("local FACES: { [string]: { { at: number, control: string, value: number } } } = {")
    for actor, track in sorted(getattr(built, "faces", {}).items()):
        lines.append(f'\t["{_escape(actor)}"] = {{')
        for key in sorted(track.keys, key=lambda k: (k.at, k.control)):
            lines.append(
                f'\t\t{{ at = {key.at:.3f}, control = "{_escape(key.control)}", '
                f"value = {key.value:.3f} }},"
            )
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    # Where each actor travels. A Roblox animation is in place, so crossing the
    # scene is the model moving — the clip never carries the character.
    lines.append(
        "local MOVES: { { actor: string, start: number, stop: number, "
        "from: Vector3, to: Vector3 } } = {"
    )
    for actor, start, stop, origin, goal in getattr(built, "moves", []):
        ox, oy, oz = origin
        gx, gy, gz = goal
        lines.append(
            f'\t{{ actor = "{_escape(actor)}", start = {start:.3f}, stop = {stop:.3f}, '
            f"from = Vector3.new({ox:g}, {oy:g}, {oz:g}), "
            f"to = Vector3.new({gx:g}, {gy:g}, {gz:g}) }},"
        )
    lines.append("}")
    lines.append("")
    lines.append("-- Cue sheet, for reference when retiming by hand.")
    lines.append(
        "local CUES: { { id: string, actor: string, start: number, stop: number, "
        "what: string } } = {"
    )
    for entry in built.schedule:
        summary = _escape((entry.cue.prompt or entry.plan.name)[:60])
        lines.append(
            f'\t{{ id = "{_escape(entry.cue.id)}", actor = "{_escape(entry.cue.actor)}", '
            f"start = {entry.start:.3f}, stop = {entry.end:.3f}, "
            f'what = "{summary}" }},'
        )
    lines.append("}")
    lines.append("")

    lines.append(
        "local SHOTS: { { id: string, position: Vector3, lookAt: string, fov: number, "
        "blend: number, drift: Vector3, kind: string, orbitSpeed: number, "
        "orbitRadius: number, followOffset: Vector3, followLag: number } } = {"
    )
    for shot in scene.shots:
        x, y, z = shot.position
        dx, dy, dz = shot.drift
        fx, fy, fz = shot.follow_offset
        lines.append(
            f'\t{{ id = "{_escape(shot.id)}", position = Vector3.new({x:g}, {y:g}, {z:g}), '
            f'lookAt = "{_escape(shot.look_at)}", fov = {shot.fov:g}, blend = {shot.blend:g}, '
            f"drift = Vector3.new({dx:g}, {dy:g}, {dz:g}), "
            f'kind = "{_escape(shot.kind)}", orbitSpeed = {shot.orbit_speed:g}, '
            f"orbitRadius = {shot.orbit_radius:g}, "
            f"followOffset = Vector3.new({fx:g}, {fy:g}, {fz:g}), "
            f"followLag = {shot.follow_lag:g} }},"
        )
    lines.append("}")
    lines.append("")

    lines.append(
        "local PROPS: { { name: string, source: string, heldBy: string?, "
        "attachTo: string, grip: Vector3 } } = {"
    )
    for prop in scene.props:
        gx, gy, gz = prop.grip
        held = f'"{_escape(prop.held_by)}"' if prop.held_by else "nil"
        lines.append(
            f'\t{{ name = "{_escape(prop.name)}", source = "{_escape(prop.source)}", '
            f'heldBy = {held}, attachTo = "{_escape(prop.attach_to)}", '
            f"grip = Vector3.new({gx:g}, {gy:g}, {gz:g}) }},"
        )
    lines.append("}")
    lines.append("")

    lines.append("-- Events with no actor: camera cuts and world effects.")
    lines.append(
        "local DIRECTOR: { { at: number, kind: string, value: string, actor: string? } } = {"
    )
    for when, event in built.director:
        actor = f'"{_escape(event.actor)}"' if event.actor else "nil"
        lines.append(
            f'\t{{ at = {when:g}, kind = "{event.kind}", '
            f'value = "{_escape(event.marker_value())}", actor = {actor} }},'
        )
    lines.append("}")
    lines.append("")

    lines.append("-- Named expressions to FACS pose blends, so scenes stay readable.")
    lines.append("local EXPRESSIONS: { [string]: { [string]: number } } = {")
    for name, poses in _FACS.items():
        entries = ", ".join(f"{k} = {v:g}" for k, v in poses.items())
        lines.append(f"\t{name} = {{ {entries} }},")
    lines.append("}")
    lines.append("")

    lines.extend(_audio_tables(sheet, mapping or {}))
    lines.append(BODY)
    return "\n".join(lines)


def _audio_tables(sheet: SpottingSheet | None, mapping: dict[str, str]) -> list[str]:
    """The soundtrack: which asset per slot, which beds, and the tension curve.

    Emitted even when nothing was spotted, so the player can reference the
    tables unconditionally rather than guarding every use.
    """
    lines: list[str] = []
    lines.append("-- Slot -> asset. Edit <Scene>.audio.json and rebuild, not this file.")
    lines.append(
        "local SOUNDS: { [string]: { asset: string, volume: number, category: string } } = {"
    )
    for slot in sheet.used() if sheet else []:
        asset = mapping.get(slot.name) or slot.default or ""
        lines.append(
            f'\t["{_escape(slot.name)}"] = {{ asset = "{_escape(asset)}", '
            f'volume = {slot.base_volume:g}, category = "{slot.category}" }},'
        )
    lines.append("}")
    lines.append("")

    lines.append("-- Beds held across a span; their volume rides the tension curve.")
    lines.append(
        "local AMBIENCE: { { slot: string, start: number, stop: number, "
        "low: number, high: number } } = {"
    )
    for bed in sheet.ambience if sheet else []:
        lines.append(
            f'\t{{ slot = "{_escape(bed.slot)}", start = {bed.start:.3f}, '
            f"stop = {bed.stop:.3f}, low = {bed.low:g}, high = {bed.high:g} }},"
        )
    lines.append("}")
    lines.append("")

    lines.append("-- How wound-up the scene is, 0-1, sampled across the take. One")
    lines.append("-- number the whole soundtrack reads: drone volume, tremor depth, filter.")
    lines.append("local TENSION: { { number } } = {")
    for when, value in sheet.tension if sheet else []:
        lines.append(f"\t{{ {when:.3f}, {value:g} }},")
    lines.append("}")
    lines.append("")
    return lines


#: The 50 poses a ``FaceControls`` instance actually has.
#:
#: Kept here so the blends below can be checked against it. Every one of these
#: is a property assignment guarded by ``pcall`` in the runtime — which means a
#: misspelled name does not error, it simply does nothing, and the expression
#: quietly comes out blank on a head that supports it perfectly well. Four of
#: the blends below were wrong in exactly that way before this list existed.
FACS_POSES: frozenset[str] = frozenset({
    "LeftEyeClosed", "RightEyeClosed", "EyesLookDown", "EyesLookLeft",
    "EyesLookRight", "EyesLookUp", "JawDrop", "JawLeft", "JawRight",
    "Pucker", "FlatPucker", "Funneler", "LipsTogether", "LipPresser",
    "LowerLipSuck", "UpperLipSuck", "MouthLeft", "MouthRight",
    "ChinRaiser", "ChinRaiserUpperLip", "Corrugator",
    "LeftLipCornerPuller", "RightLipCornerPuller",
    "LeftLipCornerDown", "RightLipCornerDown",
    "LeftLipStretcher", "RightLipStretcher",
    "LeftLowerLipDepressor", "RightLowerLipDepressor",
    "LeftUpperLipRaiser", "RightUpperLipRaiser",
    "LeftCheekRaiser", "RightCheekRaiser",
    "LeftCheekPuff", "RightCheekPuff",
    "LeftDimpler", "RightDimpler",
    "LeftInnerBrowRaiser", "RightInnerBrowRaiser",
    "LeftOuterBrowRaiser", "RightOuterBrowRaiser",
    "LeftBrowLowerer", "RightBrowLowerer",
    "LeftNoseWrinkler", "RightNoseWrinkler",
    "LeftEyeUpperLidRaiser", "RightEyeUpperLidRaiser",
    "TongueDown", "TongueOut", "TongueUp",
})

#: A small, deliberate subset of those 50 — enough to read at Roblox camera
#: distances, and named so a scene never mentions a coefficient.
_FACS: dict[str, dict[str, float]] = {
    "neutral": {},
    "smug": {"LeftLipCornerPuller": 0.75, "RightLipCornerPuller": 0.2, "LeftBrowLowerer": 0.25},
    "angry": {"LeftBrowLowerer": 0.9, "RightBrowLowerer": 0.9, "LipPresser": 0.6, "LeftNoseWrinkler": 0.4, "RightNoseWrinkler": 0.4},
    "afraid": {"LeftOuterBrowRaiser": 0.8, "RightOuterBrowRaiser": 0.8, "LeftEyeUpperLidRaiser": 0.9, "RightEyeUpperLidRaiser": 0.9, "JawDrop": 0.35},
    "surprised": {"LeftInnerBrowRaiser": 1.0, "RightInnerBrowRaiser": 1.0, "JawDrop": 0.5},
    "pain": {"LeftEyeClosed": 0.85, "RightEyeClosed": 0.85, "LeftNoseWrinkler": 0.7, "RightNoseWrinkler": 0.7, "LeftLipStretcher": 0.5, "RightLipStretcher": 0.5},
    "determined": {"LeftBrowLowerer": 0.5, "RightBrowLowerer": 0.5, "LipPresser": 0.4},
    "laughing": {"LeftLipCornerPuller": 1.0, "RightLipCornerPuller": 1.0, "JawDrop": 0.6, "LeftCheekRaiser": 0.7, "RightCheekRaiser": 0.7},
    "sad": {"LeftInnerBrowRaiser": 0.8, "RightInnerBrowRaiser": 0.8, "LeftLipCornerDown": 0.6, "RightLipCornerDown": 0.6},
}


def write_scene_script(
    built: BuiltScene,
    path: str | Path,
    *,
    folder: str = "ServerStorage.LinenAnimations",
    sheet: SpottingSheet | None = None,
    mapping: dict[str, str] | None = None,
    animations: dict[str, str] | None = None,
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        scene_script(
            built, folder=folder, sheet=sheet, mapping=mapping, animations=animations
        )
    )
    return path


def _facing_literal(facing: str | float | None) -> str:
    if facing is None:
        return "nil"
    if isinstance(facing, str):
        return f'"{_escape(facing)}"'
    return f"{float(facing):g}"


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
