"""Map a foreign skeleton's joints onto the landmark names the rigs reference.

The retargeter works on named points, not on any particular tracker, so a
skeleton from somewhere else only needs a name mapping to become a
:class:`~linen.retarget.landmarks.LandmarkTrack`.  That is what lets a clip
generated by an external text-to-motion model — SayMotion, a locally run
MoMask or MDM, a Mixamo download — go through exactly the same solve, the same
conventions and the same exporter as a FreeMoCap capture.

Two landmarks MediaPipe provides have no equivalent on an animation skeleton
and are reconstructed instead:

* **heels**, placed under the ankle at toe height, so the foot's forward
  direction comes out horizontal rather than pitched down towards the toe;
* **ears**, placed either side of the head using the head bone's own direction.
  Head pitch and roll survive this; head *yaw* does not, and follows the chest.
  Recovering it would need the source's rotation channels, which are expressed
  against each exporter's own rest pose — not worth binding the solver to.

Because every joint rotation is solved relative to its parent, which way the
source skeleton faces does not matter.  Only baked root motion notices.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from ..math3d import normalize
from ..retarget.landmarks import MEDIAPIPE_POSE, LandmarkTrack
from .bvh import BvhMotion

#: Landmarks the solver can manage without. A part whose source landmarks are
#: missing holds its parent's pose rather than guessing.
OPTIONAL = frozenset({"left_index", "right_index", "left_pinky", "right_pinky", "nose"})


@dataclass(frozen=True)
class SkeletonMapping:
    """A named correspondence from source joints to MediaPipe landmarks."""

    name: str
    #: landmark name -> candidate source joint names, first match wins.
    joints: dict[str, tuple[str, ...]]
    #: Source joint marking the top of the head, used to reconstruct ears.
    head_tip: tuple[str, ...] = ()
    notes: str = ""
    aliases: tuple[str, ...] = field(default=())

    def resolve(self, available: tuple[str, ...]) -> dict[str, str]:
        """Pick the source joint for each landmark, given what the file has."""
        lookup = {name.lower(): name for name in available}
        resolved: dict[str, str] = {}
        for landmark, candidates in self.joints.items():
            for candidate in candidates:
                match = lookup.get(candidate.lower())
                if match is not None:
                    resolved[landmark] = match
                    break
        return resolved

    def missing_required(self, available: tuple[str, ...]) -> list[str]:
        resolved = self.resolve(available)
        return sorted(set(self.joints) - set(resolved) - OPTIONAL)


#: Mixamo's naming, which is also what HumanML3D-derived BVH writers emit and
#: what most humanoid FBX rigs use, so one mapping covers SayMotion exports,
#: MoMask/MDM output and Mixamo downloads.
MIXAMO = SkeletonMapping(
    name="mixamo",
    aliases=("humanml3d", "smpl", "fbx"),
    joints={
        "left_shoulder": ("LeftArm", "mixamorig:LeftArm", "left_shoulder"),
        "right_shoulder": ("RightArm", "mixamorig:RightArm", "right_shoulder"),
        "left_elbow": ("LeftForeArm", "mixamorig:LeftForeArm", "left_elbow"),
        "right_elbow": ("RightForeArm", "mixamorig:RightForeArm", "right_elbow"),
        "left_wrist": ("LeftHand", "mixamorig:LeftHand", "left_wrist"),
        "right_wrist": ("RightHand", "mixamorig:RightHand", "right_wrist"),
        "left_index": ("LeftHandIndex1", "mixamorig:LeftHandIndex1", "LeftHand_End"),
        "right_index": ("RightHandIndex1", "mixamorig:RightHandIndex1", "RightHand_End"),
        "left_pinky": ("LeftHandPinky1", "mixamorig:LeftHandPinky1"),
        "right_pinky": ("RightHandPinky1", "mixamorig:RightHandPinky1"),
        "left_hip": ("LeftUpLeg", "mixamorig:LeftUpLeg", "left_hip"),
        "right_hip": ("RightUpLeg", "mixamorig:RightUpLeg", "right_hip"),
        "left_knee": ("LeftLeg", "mixamorig:LeftLeg", "left_knee"),
        "right_knee": ("RightLeg", "mixamorig:RightLeg", "right_knee"),
        "left_ankle": ("LeftFoot", "mixamorig:LeftFoot", "left_ankle"),
        "right_ankle": ("RightFoot", "mixamorig:RightFoot", "right_ankle"),
        "left_foot_index": ("LeftToeBase", "mixamorig:LeftToeBase", "LeftFoot_End"),
        "right_foot_index": ("RightToeBase", "mixamorig:RightToeBase", "RightFoot_End"),
        "nose": ("Head", "mixamorig:Head"),
    },
    head_tip=("HeadTop_End", "Head_End", "mixamorig:HeadTop_End"),
    notes="Mixamo / HumanML3D / most humanoid FBX rigs.",
)

#: A skeleton whose bones already carry Roblox's own part names — which is what
#: the community Blender R15 rigs use for their deform bones, and what Roblox's
#: own exporters emit. Round-tripping through Blender is the practical way to
#: get Mixamo motion onto an R15, because Mixamo exports FBX and DAE and no BVH
#: at all; Blender is the converter, and this mapping is what receives it.
ROBLOX_R15 = SkeletonMapping(
    name="r15",
    aliases=("roblox", "blender-r15"),
    joints={
        "left_shoulder": ("LeftUpperArm", "DEF_LeftUpperArm", "LeftUpperArm.L"),
        "right_shoulder": ("RightUpperArm", "DEF_RightUpperArm", "RightUpperArm.R"),
        "left_elbow": ("LeftLowerArm", "DEF_LeftLowerArm"),
        "right_elbow": ("RightLowerArm", "DEF_RightLowerArm"),
        "left_wrist": ("LeftHand", "DEF_LeftHand"),
        "right_wrist": ("RightHand", "DEF_RightHand"),
        "left_index": ("LeftHand_End",),
        "right_index": ("RightHand_End",),
        "left_hip": ("LeftUpperLeg", "DEF_LeftUpperLeg"),
        "right_hip": ("RightUpperLeg", "DEF_RightUpperLeg"),
        "left_knee": ("LeftLowerLeg", "DEF_LeftLowerLeg"),
        "right_knee": ("RightLowerLeg", "DEF_RightLowerLeg"),
        "left_ankle": ("LeftFoot", "DEF_LeftFoot"),
        "right_ankle": ("RightFoot", "DEF_RightFoot"),
        "left_foot_index": ("LeftFoot_End", "LeftToe"),
        "right_foot_index": ("RightFoot_End", "RightToe"),
        "nose": ("Head", "DEF_Head"),
    },
    head_tip=("Head_End", "HeadTop_End"),
    notes="Roblox part names, as used by Blender R15 rigs and Roblox exporters.",
)

SKELETONS: dict[str, SkeletonMapping] = {MIXAMO.name: MIXAMO, ROBLOX_R15.name: ROBLOX_R15}
for _mapping in list(SKELETONS.values()):
    for _alias in _mapping.aliases:
        SKELETONS[_alias] = _mapping


def get_skeleton(name: str) -> SkeletonMapping:
    try:
        return SKELETONS[name.lower()]
    except KeyError:
        raise ValueError(
            f"unknown skeleton {name!r}; known: {', '.join(sorted(SKELETONS))}"
        ) from None


def to_landmark_track(
    motion: BvhMotion,
    mapping: SkeletonMapping,
    *,
    units: str = "cm",
    fps: float | None = None,
) -> LandmarkTrack:
    """Convert parsed BVH into a landmark track in Roblox axes and metres."""
    scale = {"mm": 0.001, "cm": 0.01, "m": 1.0}
    if units not in scale:
        raise ValueError(f"unknown units {units!r}; expected one of {', '.join(scale)}")

    missing = mapping.missing_required(motion.names)
    if missing:
        raise ValueError(
            f"{mapping.name}: this file has no joint for {', '.join(missing)}. "
            f"Joints present: {', '.join(motion.names[:12])}…"
        )

    world = motion.world_positions() * scale[units]
    index = {name: i for i, name in enumerate(motion.names)}
    resolved = mapping.resolve(motion.names)

    frames = world.shape[0]
    positions = np.full((frames, len(MEDIAPIPE_POSE), 3), np.nan)
    for landmark, joint in resolved.items():
        positions[:, MEDIAPIPE_POSE.index(landmark), :] = world[:, index[joint]]

    _reconstruct_heels(positions)
    _reconstruct_ears(positions, world, index, mapping)

    # BVH is Y-up right-handed, the same convention Roblox uses.
    return LandmarkTrack(positions, fps if fps is not None else motion.fps)


def _reconstruct_heels(positions: np.ndarray) -> None:
    """Put each heel under its ankle at toe height."""
    for side in ("left", "right"):
        ankle = positions[:, MEDIAPIPE_POSE.index(f"{side}_ankle"), :]
        toe = positions[:, MEDIAPIPE_POSE.index(f"{side}_foot_index"), :]
        heel = ankle.copy()
        heel[:, 1] = toe[:, 1]
        positions[:, MEDIAPIPE_POSE.index(f"{side}_heel"), :] = heel


def _reconstruct_ears(
    positions: np.ndarray,
    world: np.ndarray,
    index: dict[str, int],
    mapping: SkeletonMapping,
) -> None:
    """Place ears either side of the head, along the body's lateral axis."""
    head = next((index[n] for n in mapping.joints["nose"] if n in index), None)
    tip = next((index[n] for n in mapping.head_tip if n in index), None)
    if head is None or tip is None:
        return

    head_pos = world[:, head]
    head_up = normalize(world[:, tip] - head_pos)

    left_shoulder = positions[:, MEDIAPIPE_POSE.index("left_shoulder"), :]
    right_shoulder = positions[:, MEDIAPIPE_POSE.index("right_shoulder"), :]
    hips = 0.5 * (
        positions[:, MEDIAPIPE_POSE.index("left_hip"), :]
        + positions[:, MEDIAPIPE_POSE.index("right_hip"), :]
    )
    spine_up = normalize(0.5 * (left_shoulder + right_shoulder) - hips)
    back = normalize(np.cross(normalize(right_shoulder - left_shoulder), spine_up))

    lateral = normalize(np.cross(head_up, back))
    reach = 0.5 * np.linalg.norm(world[:, tip] - head_pos, axis=-1, keepdims=True)

    positions[:, MEDIAPIPE_POSE.index("left_ear"), :] = head_pos - lateral * reach
    positions[:, MEDIAPIPE_POSE.index("right_ear"), :] = head_pos + lateral * reach
