// Generated by `python -m linen.export.preview` — do not edit by hand.
export interface RigPart {
  name: string;
  parent: string | null;
  joint: string | null;
  size: [number, number, number];
  pivot: [number, number, number];
  offsetFromPivot: [number, number, number];
}

export interface RigDefinition {
  name: string;
  parts: RigPart[];
}

export const RIGS: Record<string, RigDefinition> = {
  R15: {
  "name": "R15",
  "parts": [
    {
      "name": "HumanoidRootPart",
      "parent": null,
      "joint": null,
      "size": [
        2.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.0,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        1.0,
        0.0
      ]
    },
    {
      "name": "LowerTorso",
      "parent": "HumanoidRootPart",
      "joint": "Root",
      "size": [
        1.33,
        0.41,
        0.72
      ],
      "pivot": [
        0.0,
        -0.205,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        0.205,
        0.0
      ]
    },
    {
      "name": "UpperTorso",
      "parent": "LowerTorso",
      "joint": "Waist",
      "size": [
        1.3,
        1.7,
        0.84
      ],
      "pivot": [
        0.0,
        -0.05599999999999994,
        0.051
      ],
      "offsetFromPivot": [
        0.0,
        0.85,
        0.0
      ]
    },
    {
      "name": "Head",
      "parent": "UpperTorso",
      "joint": "Neck",
      "size": [
        1.15,
        1.18,
        1.13
      ],
      "pivot": [
        0.0,
        0.57,
        -0.067
      ],
      "offsetFromPivot": [
        0.0,
        0.59,
        0.0
      ]
    },
    {
      "name": "LeftUpperArm",
      "parent": "UpperTorso",
      "joint": "LeftShoulder",
      "size": [
        0.75,
        0.89,
        0.58
      ],
      "pivot": [
        -0.678,
        0.29900000000000004,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.44500000000000006,
        0.0
      ]
    },
    {
      "name": "LeftLowerArm",
      "parent": "LeftUpperArm",
      "joint": "LeftElbow",
      "size": [
        0.66,
        0.9,
        0.59
      ],
      "pivot": [
        0.0,
        -0.23000000000000004,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.45,
        0.0
      ]
    },
    {
      "name": "LeftHand",
      "parent": "LeftLowerArm",
      "joint": "LeftWrist",
      "size": [
        0.55,
        0.59,
        0.53
      ],
      "pivot": [
        0.0,
        -0.39899999999999997,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.295,
        0.0
      ]
    },
    {
      "name": "RightUpperArm",
      "parent": "UpperTorso",
      "joint": "RightShoulder",
      "size": [
        0.75,
        0.89,
        0.58
      ],
      "pivot": [
        0.678,
        0.29900000000000004,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.44500000000000006,
        0.0
      ]
    },
    {
      "name": "RightLowerArm",
      "parent": "RightUpperArm",
      "joint": "RightElbow",
      "size": [
        0.66,
        0.9,
        0.59
      ],
      "pivot": [
        0.0,
        -0.23000000000000004,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.45,
        0.0
      ]
    },
    {
      "name": "RightHand",
      "parent": "RightLowerArm",
      "joint": "RightWrist",
      "size": [
        0.55,
        0.59,
        0.53
      ],
      "pivot": [
        0.0,
        -0.39899999999999997,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.295,
        0.0
      ]
    },
    {
      "name": "LeftUpperLeg",
      "parent": "LowerTorso",
      "joint": "LeftHip",
      "size": [
        0.66,
        1.66,
        0.66
      ],
      "pivot": [
        -0.328,
        -0.0010000000000000009,
        0.011
      ],
      "offsetFromPivot": [
        0.0,
        -0.83,
        0.0
      ]
    },
    {
      "name": "LeftLowerLeg",
      "parent": "LeftUpperLeg",
      "joint": "LeftKnee",
      "size": [
        0.61,
        1.17,
        0.61
      ],
      "pivot": [
        -0.025,
        -0.31800000000000006,
        -0.021
      ],
      "offsetFromPivot": [
        0.0,
        -0.585,
        0.0
      ]
    },
    {
      "name": "LeftFoot",
      "parent": "LeftLowerLeg",
      "joint": "LeftAnkle",
      "size": [
        0.61,
        0.56,
        0.86
      ],
      "pivot": [
        0.0,
        -0.421,
        0.318
      ],
      "offsetFromPivot": [
        0.0,
        0.0,
        -0.43
      ]
    },
    {
      "name": "RightUpperLeg",
      "parent": "LowerTorso",
      "joint": "RightHip",
      "size": [
        0.66,
        1.66,
        0.66
      ],
      "pivot": [
        0.328,
        -0.0010000000000000009,
        0.011
      ],
      "offsetFromPivot": [
        0.0,
        -0.83,
        0.0
      ]
    },
    {
      "name": "RightLowerLeg",
      "parent": "RightUpperLeg",
      "joint": "RightKnee",
      "size": [
        0.61,
        1.17,
        0.61
      ],
      "pivot": [
        0.025,
        -0.31800000000000006,
        -0.021
      ],
      "offsetFromPivot": [
        0.0,
        -0.585,
        0.0
      ]
    },
    {
      "name": "RightFoot",
      "parent": "RightLowerLeg",
      "joint": "RightAnkle",
      "size": [
        0.61,
        0.56,
        0.86
      ],
      "pivot": [
        0.0,
        -0.421,
        0.318
      ],
      "offsetFromPivot": [
        0.0,
        0.0,
        -0.43
      ]
    }
  ]
},
  R6: {
  "name": "R6",
  "parts": [
    {
      "name": "HumanoidRootPart",
      "parent": null,
      "joint": null,
      "size": [
        2.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.0,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        1.0,
        0.0
      ]
    },
    {
      "name": "Torso",
      "parent": "HumanoidRootPart",
      "joint": "RootJoint",
      "size": [
        2.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.0,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        1.0,
        0.0
      ]
    },
    {
      "name": "Head",
      "parent": "Torso",
      "joint": "Neck",
      "size": [
        2.0,
        1.0,
        1.0
      ],
      "pivot": [
        0.0,
        1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        0.5,
        0.0
      ]
    },
    {
      "name": "Left Arm",
      "parent": "Torso",
      "joint": "Left Shoulder",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        -1.5,
        1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    },
    {
      "name": "Right Arm",
      "parent": "Torso",
      "joint": "Right Shoulder",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        1.5,
        1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    },
    {
      "name": "Left Leg",
      "parent": "Torso",
      "joint": "Left Hip",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        -0.5,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    },
    {
      "name": "Right Leg",
      "parent": "Torso",
      "joint": "Right Hip",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.5,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    }
  ]
},
};

export type RigName = keyof typeof RIGS;

/** Suggested durations in seconds; null means the plan's natural length.
 *  Any other value is accepted too — there is no upper limit beyond a
 *  typo guard, because plans are composed rather than sampled from a
 *  model with a fixed training window. */
export const DURATION_PRESETS: (number | null)[] = [null, 3, 5, 10, 15, 30, 60];

/** How to reach a requested duration. */
export const FIT_STRATEGIES = ["auto", "cycle", "repeat", "stretch", "trim"] as const;

/** Root handling, mirroring the CLI's --motion. */
export const MOTION_MODES = [
  { id: "in-place", label: "In-place", hint: "Root locked. Good for idle and run cycles." },
  { id: "natural", label: "Natural", hint: "Character moves through space." },
  { id: "loop", label: "Loop", hint: "Seamless in-place loop." },
] as const;
