// Generated by `python -m linen.export.preview` — do not edit by hand.
export interface RigPart {
  name: string;
  parent: string | null;
  joint: string | null;
  size: [number, number, number];
  pivot: [number, number, number];
  offsetFromPivot: [number, number, number];
}

export interface RigDefinition {
  name: string;
  parts: RigPart[];
}

export const RIGS: Record<string, RigDefinition> = {
  R15: {
  "name": "R15",
  "parts": [
    {
      "name": "HumanoidRootPart",
      "parent": null,
      "joint": null,
      "size": [
        2.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.0,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        1.0,
        0.0
      ]
    },
    {
      "name": "LowerTorso",
      "parent": "HumanoidRootPart",
      "joint": "Root",
      "size": [
        2.0,
        0.4,
        1.0
      ],
      "pivot": [
        0.0,
        -0.2,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        0.2,
        0.0
      ]
    },
    {
      "name": "UpperTorso",
      "parent": "LowerTorso",
      "joint": "Waist",
      "size": [
        2.0,
        1.6,
        1.0
      ],
      "pivot": [
        0.0,
        0.19999999999999996,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        0.8,
        0.0
      ]
    },
    {
      "name": "Head",
      "parent": "UpperTorso",
      "joint": "Neck",
      "size": [
        2.0,
        1.0,
        1.0
      ],
      "pivot": [
        0.0,
        0.8,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        0.5,
        0.0
      ]
    },
    {
      "name": "LeftUpperArm",
      "parent": "UpperTorso",
      "joint": "LeftShoulder",
      "size": [
        1.0,
        1.21,
        1.0
      ],
      "pivot": [
        -1.5,
        1.005,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.6049999999999999,
        0.0
      ]
    },
    {
      "name": "LeftLowerArm",
      "parent": "LeftUpperArm",
      "joint": "LeftElbow",
      "size": [
        1.0,
        1.16,
        1.0
      ],
      "pivot": [
        0.0,
        -0.61,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.58,
        0.0
      ]
    },
    {
      "name": "LeftHand",
      "parent": "LeftLowerArm",
      "joint": "LeftWrist",
      "size": [
        1.0,
        0.62,
        1.0
      ],
      "pivot": [
        0.0,
        -0.5800000000000001,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.30999999999999994,
        0.0
      ]
    },
    {
      "name": "RightUpperArm",
      "parent": "UpperTorso",
      "joint": "RightShoulder",
      "size": [
        1.0,
        1.21,
        1.0
      ],
      "pivot": [
        1.5,
        1.005,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.6049999999999999,
        0.0
      ]
    },
    {
      "name": "RightLowerArm",
      "parent": "RightUpperArm",
      "joint": "RightElbow",
      "size": [
        1.0,
        1.16,
        1.0
      ],
      "pivot": [
        0.0,
        -0.61,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.58,
        0.0
      ]
    },
    {
      "name": "RightHand",
      "parent": "RightLowerArm",
      "joint": "RightWrist",
      "size": [
        1.0,
        0.62,
        1.0
      ],
      "pivot": [
        0.0,
        -0.5800000000000001,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.30999999999999994,
        0.0
      ]
    },
    {
      "name": "LeftUpperLeg",
      "parent": "LowerTorso",
      "joint": "LeftHip",
      "size": [
        1.0,
        1.55,
        1.0
      ],
      "pivot": [
        -0.5,
        -0.20499999999999996,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.775,
        0.0
      ]
    },
    {
      "name": "LeftLowerLeg",
      "parent": "LeftUpperLeg",
      "joint": "LeftKnee",
      "size": [
        1.0,
        1.51,
        1.0
      ],
      "pivot": [
        0.0,
        -0.775,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.755,
        0.0
      ]
    },
    {
      "name": "LeftFoot",
      "parent": "LeftLowerLeg",
      "joint": "LeftAnkle",
      "size": [
        1.0,
        0.94,
        1.0
      ],
      "pivot": [
        0.0,
        -1.22,
        0.5
      ],
      "offsetFromPivot": [
        0.0,
        0.0,
        -0.5
      ]
    },
    {
      "name": "RightUpperLeg",
      "parent": "LowerTorso",
      "joint": "RightHip",
      "size": [
        1.0,
        1.55,
        1.0
      ],
      "pivot": [
        0.5,
        -0.20499999999999996,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.775,
        0.0
      ]
    },
    {
      "name": "RightLowerLeg",
      "parent": "RightUpperLeg",
      "joint": "RightKnee",
      "size": [
        1.0,
        1.51,
        1.0
      ],
      "pivot": [
        0.0,
        -0.775,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -0.755,
        0.0
      ]
    },
    {
      "name": "RightFoot",
      "parent": "RightLowerLeg",
      "joint": "RightAnkle",
      "size": [
        1.0,
        0.94,
        1.0
      ],
      "pivot": [
        0.0,
        -1.22,
        0.5
      ],
      "offsetFromPivot": [
        0.0,
        0.0,
        -0.5
      ]
    }
  ]
},
  R6: {
  "name": "R6",
  "parts": [
    {
      "name": "HumanoidRootPart",
      "parent": null,
      "joint": null,
      "size": [
        2.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.0,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        1.0,
        0.0
      ]
    },
    {
      "name": "Torso",
      "parent": "HumanoidRootPart",
      "joint": "RootJoint",
      "size": [
        2.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.0,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        1.0,
        0.0
      ]
    },
    {
      "name": "Head",
      "parent": "Torso",
      "joint": "Neck",
      "size": [
        2.0,
        1.0,
        1.0
      ],
      "pivot": [
        0.0,
        1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        0.5,
        0.0
      ]
    },
    {
      "name": "Left Arm",
      "parent": "Torso",
      "joint": "Left Shoulder",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        -1.5,
        1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    },
    {
      "name": "Right Arm",
      "parent": "Torso",
      "joint": "Right Shoulder",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        1.5,
        1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    },
    {
      "name": "Left Leg",
      "parent": "Torso",
      "joint": "Left Hip",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        -0.5,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    },
    {
      "name": "Right Leg",
      "parent": "Torso",
      "joint": "Right Hip",
      "size": [
        1.0,
        2.0,
        1.0
      ],
      "pivot": [
        0.5,
        -1.0,
        0.0
      ],
      "offsetFromPivot": [
        0.0,
        -1.0,
        0.0
      ]
    }
  ]
},
};

export type RigName = keyof typeof RIGS;

/** Suggested durations in seconds; null means the plan's natural length.
 *  Any other value is accepted too — there is no upper limit beyond a
 *  typo guard, because plans are composed rather than sampled from a
 *  model with a fixed training window. */
export const DURATION_PRESETS: (number | null)[] = [null, 3, 5, 10, 15, 30, 60];

/** How to reach a requested duration. */
export const FIT_STRATEGIES = ["auto", "cycle", "repeat", "stretch", "trim"] as const;

/** Root handling, mirroring the CLI's --motion. */
export const MOTION_MODES = [
  { id: "in-place", label: "In-place", hint: "Root locked. Good for idle and run cycles." },
  { id: "natural", label: "Natural", hint: "Character moves through space." },
  { id: "loop", label: "Loop", hint: "Seamless in-place loop." },
] as const;
