"""Emit the rig data the Roblox-side runtime needs, as a Luau module.

The runtime is a separate program from the rest of Linen — it ships inside a
Roblox place and runs every frame, where the exporter runs once on a laptop.
The one thing they must agree on is the rig: the same joint names, the same
hierarchy, the same idea of what a shoulder can do. Hand-copying that into Luau
is how the physics rig quietly stops matching the animation rig, so it is
generated from the definitions the exporter and the pose book already use.
"""

from __future__ import annotations

from pathlib import Path

from ..rigs import RIGS, RigDefinition
from ..rigs.limits import JointKind, limits_for

HEADER = """\
--!strict
-- Generated by `python -m linen.export.luau`. Do not edit by hand.
--
-- Joint limits and drive gains for physics-driven characters. Angles are
-- degrees, matching the units every Roblox constraint property uses.
--
-- `kind` decides which constraint expresses the joint:
--   "ball"  -> BallSocketConstraint, LimitsEnabled, UpperAngle = swing,
--              TwistLimitsEnabled, TwistLowerAngle/TwistUpperAngle = twist.
--   "hinge" -> HingeConstraint, LimitsEnabled, LowerAngle/UpperAngle.
--              Elbows and knees. A cone here lets them bend sideways.
--   "fixed" -> welded during ragdoll; the root is the physics capsule, not a
--              body part, and pivoting about it makes a character fold in half.
"""


def rig_limits_module() -> str:
    lines = [HEADER, "", "local RigLimits = {}", ""]
    lines.append("export type JointKind = \"ball\" | \"hinge\" | \"fixed\"")
    lines.append("")
    lines.append("export type JointLimit = {")
    lines.append("\tkind: JointKind,")
    lines.append("\tswing: number,")
    lines.append("\ttwistLower: number,")
    lines.append("\ttwistUpper: number,")
    lines.append("\tlower: number,")
    lines.append("\tupper: number,")
    lines.append("\tresponsiveness: number,")
    lines.append("\tmaxTorque: number,")
    lines.append("}")
    lines.append("")
    lines.append("export type RigSpec = {")
    lines.append("\tparts: { string },")
    lines.append("\tparents: { [string]: string },")
    lines.append("\tjoints: { [string]: string },")
    lines.append("\tlimits: { [string]: JointLimit },")
    lines.append("}")
    lines.append("")
    lines.append("RigLimits.rigs = {} :: { [string]: RigSpec }")
    lines.append("")

    for name, rig in sorted(RIGS.items()):
        lines.extend(_rig_block(name, rig))
        lines.append("")

    lines.append("function RigLimits.get(rigName: string): RigSpec?")
    lines.append("\treturn RigLimits.rigs[rigName]")
    lines.append("end")
    lines.append("")
    lines.append("--[[ The rig a character is built on, or nil when it is neither. ]]")
    lines.append("function RigLimits.detect(character: Model): string?")
    lines.append("\tfor rigName, spec in RigLimits.rigs do")
    lines.append("\t\tlocal complete = true")
    lines.append("\t\tfor _, part in spec.parts do")
    lines.append("\t\t\tif character:FindFirstChild(part) == nil then")
    lines.append("\t\t\t\tcomplete = false")
    lines.append("\t\t\t\tbreak")
    lines.append("\t\t\tend")
    lines.append("\t\tend")
    lines.append("\t\tif complete then")
    lines.append("\t\t\treturn rigName")
    lines.append("\t\tend")
    lines.append("\tend")
    lines.append("\treturn nil")
    lines.append("end")
    lines.append("")
    lines.append("return RigLimits")
    return "\n".join(lines) + "\n"


def _rig_block(name: str, rig: RigDefinition) -> list[str]:
    table = limits_for(name)
    lines = [f"RigLimits.rigs[\"{name}\"] = {{"]

    lines.append("\tparts = {")
    for part in rig.parts:
        lines.append(f'\t\t"{part.name}",')
    lines.append("\t},")

    lines.append("\tparents = {")
    for part in rig.parts[1:]:
        lines.append(f'\t\t["{part.name}"] = "{part.parent}",')
    lines.append("\t},")

    lines.append("\t-- part name -> the Motor6D that attaches it to its parent")
    lines.append("\tjoints = {")
    for part in rig.parts[1:]:
        lines.append(f'\t\t["{part.name}"] = "{part.joint}",')
    lines.append("\t},")

    lines.append("\tlimits = {")
    for part in rig.parts[1:]:
        limit = table[part.joint]
        lines.append(f'\t\t["{part.joint}"] = {{')
        lines.append(f'\t\t\tkind = "{limit.kind.value}",')
        if limit.kind is JointKind.BALL:
            lines.append(f"\t\t\tswing = {limit.swing:g},")
            lines.append(f"\t\t\ttwistLower = {limit.twist[0]:g},")
            lines.append(f"\t\t\ttwistUpper = {limit.twist[1]:g},")
            lines.append("\t\t\tlower = 0, upper = 0,")
        elif limit.kind is JointKind.HINGE:
            lines.append("\t\t\tswing = 0, twistLower = 0, twistUpper = 0,")
            lines.append(f"\t\t\tlower = {limit.lower:g},")
            lines.append(f"\t\t\tupper = {limit.upper:g},")
        else:
            lines.append("\t\t\tswing = 0, twistLower = 0, twistUpper = 0,")
            lines.append("\t\t\tlower = 0, upper = 0,")
        lines.append(f"\t\t\tresponsiveness = {limit.responsiveness:g},")
        lines.append(f"\t\t\tmaxTorque = {limit.max_torque:g},")
        lines.append("\t\t},")
    lines.append("\t},")
    lines.append("}")
    return lines


def write_rig_limits(path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rig_limits_module())
    return path


if __name__ == "__main__":
    import sys

    target = Path(sys.argv[1] if len(sys.argv) > 1 else "runtime/RigLimits.luau")
    print(write_rig_limits(target))
