"""JSON for the viewport: rig geometry, and clips sampled every frame.

The Roblox exporter drops frames the engine can interpolate back; the viewport
wants the opposite, a dense track it can index by frame with no maths, so this
is a separate serialiser rather than a flag on the other one.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from ..clip import AnimationClip
from ..rigs import RIGS, RigDefinition


def rig_to_dict(rig: RigDefinition) -> dict[str, Any]:
    return {
        "name": rig.name,
        "parts": [
            {
                "name": part.name,
                "parent": part.parent,
                "joint": part.joint,
                "size": list(part.size),
                "pivot": list(part.pivot),
                "offsetFromPivot": [
                    o - p for o, p in zip(part.rest_offset, part.pivot)
                ],
            }
            for part in rig.parts
        ],
    }


def clip_to_dict(clip: AnimationClip) -> dict[str, Any]:
    """A clip as flat per-part quaternion arrays, xyzw, frame-major."""
    return {
        "name": clip.name,
        "rig": clip.rig.name,
        "fps": clip.fps,
        "frameCount": clip.frame_count,
        "loop": clip.loop,
        "priority": clip.priority,
        "rotations": {
            part: [round(float(v), 6) for v in track.reshape(-1)]
            for part, track in clip.rotations.items()
        },
        "rootPositions": None
        if clip.root_positions is None
        else [round(float(v), 5) for v in np.asarray(clip.root_positions).reshape(-1)],
    }


def write_preview(clip: AnimationClip, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(clip_to_dict(clip)))
    return path


def write_rig_module(path: str | Path) -> Path:
    """Emit the rig definitions as a TypeScript module for the viewport.

    Generated rather than hand-maintained: a part list that disagrees with the
    exporter's would show a rig in the viewport that does not match the file
    Studio receives.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = ",\n".join(
        f"  {name}: {json.dumps(rig_to_dict(rig), indent=2)}"
        for name, rig in sorted(RIGS.items())
    )
    path.write_text(
        "// Generated by `python -m linen.export.preview` — do not edit by hand.\n"
        "export interface RigPart {\n"
        "  name: string;\n"
        "  parent: string | null;\n"
        "  joint: string | null;\n"
        "  size: [number, number, number];\n"
        "  pivot: [number, number, number];\n"
        "  offsetFromPivot: [number, number, number];\n"
        "}\n\n"
        "export interface RigDefinition {\n"
        "  name: string;\n"
        "  parts: RigPart[];\n"
        "}\n\n"
        f"export const RIGS: Record<string, RigDefinition> = {{\n{body},\n}};\n\n"
        "export type RigName = keyof typeof RIGS;\n"
    )
    return path


if __name__ == "__main__":
    import sys

    target = Path(sys.argv[1] if len(sys.argv) > 1 else "viewport/rigs.generated.ts")
    print(write_rig_module(target))
